name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install Go 1.18
        run: |
          go install golang.org/dl/go1.18rc1@latest
          go1.18rc1 download
          cp $(which go1.18rc1) $(which go)
          go version

      - name: Check out into the root
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...
